project: water-quality-template
storage:
  - name: data
    type: s3
scripts:
  - name: downloader
    run_every: 1440 # Download images every day
    run_on_start: True
  - name: water-quality
    run_every: 1440
    run_on_start: True
    wait_for:
      - downloader
apis:
  - name: analytics
    port: 8021
    host: localhost
  - name: xyz
    port: 8022
    host: localhost
uis:
  - name: map
    # command: npm run dev # for local development
    command: npm run deploy
    port: 5173
    runtime: node
    env:
      ANALYTICS_URL: api.analytics
      XYZ_URL: api.xyz
